Harvin/Models/Administrador.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Web;

namespace Harvin.Models {
    [Table("Administradores")]
    public class Administrador {
        [Key]
        public int AdministradorId { get; set; }

        [Display(Name = "Nome Completo")]
        public string AdministradorNome { get; set; }

        [Display(Name = "CPF")]
        public string AdministradorCpf { get; set; }

        [Display(Name = "Telefone")]
        public string AdministradorTelefone { get; set; }

        [Display(Name = "Endereço")]
        public string AdministradorEndereco { get; set; }

        [Display(Name = "E-mail")]
        public string AdministradorEmail { get; set; }

        [Display(Name = "Senha")]
        [DataType(DataType.Password)]
        public string AdministradorSenha { get; set; }
    }
}

Harvin/Controllers/AdministradorController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Harvin.Models;
using Harvin.DAO;

namespace Harvin.Controllers {
    public class AdministradorController : Controller {

        // GET: Administrador
        public ActionResult Index() {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a != null) {
                return View(UsuarioDAO.ListarUsuarios());
            }else {
                return RedirectToAction("Login");
            }
        }

        // GET: Administrador/Details/5
        public ActionResult Detalhes(int? id) {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a != null) {
                if (id == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Administrador administrador = AdministradorDAO.BuscarAdministradorPorId(id);
                if (administrador == null) {
                    return HttpNotFound();
                }
                return View(administrador);
            } else {
                return RedirectToAction("Login");
            }            
        }

        // GET: Administrador/Create
        public ActionResult Criar() {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a == null) {
                return View();
            } else {
                return RedirectToAction("Login");
            }
        }

        // POST: Administrador/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar([Bind(Include = "AdministradorId,AdministradorNome,AdministradorCpf,AdministradorTelefone,AdministradorEndereco,AdministradorEmail,AdministradorSenha")] Administrador administrador) {
            if (ModelState.IsValid) {
                Administrador a = new Administrador();
                a = LoginAdminDAO.RetornaAdminLogado();
                if (a == null) {
                    Administrador admin = new Administrador();
                    admin.AdministradorNome = administrador.AdministradorNome;
                    admin.AdministradorCpf = administrador.AdministradorCpf;
                    admin.AdministradorTelefone = administrador.AdministradorTelefone;
                    admin.AdministradorEndereco = administrador.AdministradorEndereco;
                    admin.AdministradorEmail = administrador.AdministradorEmail;
                    admin.AdministradorSenha = administrador.AdministradorSenha;

                    if (AdministradorDAO.VerificaCpfCadastro(admin.AdministradorCpf)) {
                        ViewBag.Mensagem = "CPF já cadastrado";
                        return RedirectToAction("Create");
                    }
                    else if(AdministradorDAO.AdicionarAdministrador(administrador)) {
                        return RedirectToAction("Login");
                    }
                }
            } else {
                return RedirectToAction("Login");
            }
            return View(administrador);

        }

        // GET: Administrador/Edit/5
        public ActionResult Editar(int? id) {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a != null) {
                if (id == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Administrador administrador = AdministradorDAO.BuscarAdministradorPorId(id);
                if (administrador == null) {
                    return HttpNotFound();
                }
                return View(administrador);
            } else {
                return RedirectToAction("Login");
            }
        }

        // POST: Administrador/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Editar([Bind(Include = "AdministradorId,AdministradorNome,AdministradorCpf,AdministradorTelefone,AdministradorEndereco,AdministradorEmail,AdministradorSenha")] Administrador administrador) {
            if (ModelState.IsValid) {
                Administrador a = new Administrador();
                a = LoginAdminDAO.RetornaAdminLogado();
                if (a != null) {
                    Administrador adminAux = AdministradorDAO.BuscarAdministradorPorId(administrador.AdministradorId);
                    adminAux.AdministradorNome = administrador.AdministradorNome;
                    adminAux.AdministradorTelefone = administrador.AdministradorTelefone;
                    adminAux.AdministradorEndereco = administrador.AdministradorEndereco;
                    adminAux.AdministradorEmail = administrador.AdministradorEmail;
                    adminAux.AdministradorSenha = administrador.AdministradorSenha;

                    if (AdministradorDAO.AtualizarAdministrador(adminAux)) {
                        return RedirectToAction("Index");
                    }
                }
                return View(administrador);
            } else {
                return RedirectToAction("Login");
            }
        }

        // GET: Administrador/Delete/5
        public ActionResult Deletar(int? id) {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a != null) {
                if (id == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Administrador administrador = AdministradorDAO.BuscarAdministradorPorId(id);
                if (administrador == null) {
                    return HttpNotFound();
                }
                return View(administrador);
            } else {
                return RedirectToAction("Login");
            }


        }

        // POST: Administrador/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int? id) {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a != null) {
                Administrador administrador = AdministradorDAO.BuscarAdministradorPorId(id);
                AdministradorDAO.RemoverAdministrador(administrador);
                return RedirectToAction("Index");
            } else {
                return RedirectToAction("Login");
            }
        }


        //GET:LOGIN
        public ActionResult Login() {
            Administrador a = new Administrador();
            a = LoginAdminDAO.RetornaAdminLogado();
            if (a != null) {
                return RedirectToAction("Index");
            } else {
                return View();
            }
        }

        // POST: Usuario/Login
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Login([Bind(Include = "AdministradorCpf,AdministradorSenha")] Administrador administrador) {
            Administrador a = new Administrador();
            if (ModelState.IsValid) {
                a.AdministradorCpf = administrador.AdministradorCpf;
                a.AdministradorSenha = administrador.AdministradorSenha;

                a = AdministradorDAO.LoginAdministrador(a);

                if (a != null) { // DIFERENTE DE 0 ENTAO É A ID DO USUARIO
                    LoginAdminDAO.AdicionaLoginAdmin(a);
                    return RedirectToAction("Index");
                } else {
                    ModelState.AddModelError("", "CPF e/ou Senha Inválido(s)");
                }
            }
            return View();
        }

        public ActionResult Logoff() {
            Guid guid = Guid.NewGuid();
            Session["Sessao"] = guid.ToString();
            return RedirectToAction("Login");
        }

    }
}

Harvin/Controllers/EstarController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Harvin.Models;
using Harvin.DAO;

namespace Harvin.Controllers {
    public class EstarController : Controller {
        private static Automovel a = new Automovel();


        // GET: Estar
        public ActionResult Index() {
            if (LoginAdminDAO.RetornaAdminLogado() != null) {
                ViewBag.Mensagem = "O carro selecionado já está estacionado"; 
                return View(EstarDAO.ListarEstares());
            }else {
                return RedirectToAction("Login", "Administrador");
            }
        }

        // GET: Estar/Details/5
        public ActionResult Detalhes(int? id) {
            if (LoginAdminDAO.RetornaAdminLogado() != null) {
                if (id == null) {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }
                Estar estar = EstarDAO.BuscarEstarPorId(id);
                if (estar == null) {
                    return HttpNotFound();
                }
                return View(estar);
            }else {
                return RedirectToAction("Login", "Administrador");
            }


        }

        // GET: Estar/Create
        public ActionResult Criar(Automovel automovel) {
            //PROCURA QUAL O AUTOMOVEL
            if (UsuarioDAO.RetornarUsuarioLogado() != null) {
                Estar e = new Estar();

                //VERIFICA SE AUTOMOVEL JÁ ESTÁ ESTACIONADO
                if (EstarDAO.VerificaCarroEstacionado(automovel.AutomovelId) != null) {
                    return RedirectToAction("Index", "Usuario");
                }
                a = automovel;
                e.EstarAutomovel = automovel;
                e.EstarDataHorario = DateTime.Now;
                e.EstarHorarioFinal = e.EstarDataHorario.AddHours(1);
                return View(e);
            }else {
                return RedirectToAction("Login", "Usuario");
            }
        }

        // POST: Estar/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Criar() {
            if (ModelState.IsValid) {
                Estar e = new Estar();
                e.EstarDataHorario = DateTime.Now;
                e.EstarHorarioFinal = e.EstarDataHorario.AddHours(1);
                e.EstarAutomovel = AutomovelDAO.BuscarAutomovelPorId(a.AutomovelId);
                e.EstarUsuario = UsuarioDAO.RetornarUsuarioLogado();

                if (e.EstarUsuario.UsuarioSaldo < 2) {
                    ViewBag.Mensagem = "Saldo Insuficiente";
                    return View();
                }else {
                    if (EstarDAO.AdicionarEstar(e)) {
                        Usuario u = new Usuario();
                        u = UsuarioDAO.BuscarUsuarioPorId(e.EstarUsuario.UsuarioId);
                        u.UsuarioSaldo = u.UsuarioSaldo - 2;

                        if (UsuarioDAO.AtualizarUsuario(u)) {
                            return RedirectToAction("Index", "Usuario");
                        }
                    } else {
                        ModelState.AddModelError("", "Erro ao Estacionar o Automóvel - Banco de Dados");
                        return RedirectToAction("Create");
                    }
                }
            }
            return RedirectToAction("Index", "Usuario");
        }

        //// GET: Estar/Edit/5
        //public ActionResult Edit(int? id) {
        //    if (id == null) {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Estar estar = EstarDAO.BuscarEstarPorId(id);
        //    if (estar == null) {
        //        return HttpNotFound();
        //    }
        //    return View(estar);
        //}

        // POST: Estar/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        //[HttpPost]
        //[ValidateAntiForgeryToken]
        //public ActionResult Edit([Bind(Include = "EstarId, EstarData,EstarHorario,EstarRua,EstarAtivo")] Estar estar, int UsuarioId, int AutomovelId) {
        //    if (ModelState.IsValid) {
        //        Estar estarAux = EstarDAO.BuscarEstarPorId(estar.EstarId);
        //        estarAux.EstarUsuario = estar.EstarUsuario;
        //        estarAux.EstarAutomovel = AutomovelDAO.BuscarAutomovelPorId(AutomovelId);
        //        estarAux.EstarUsuario = UsuarioDAO.BuscarUsuarioPorId(UsuarioId);
        //        estarAux.EstarRua = estar.EstarRua;
        //        estarAux.EstarDataHorario = DateTime.Now;
        //        estarAux.EstarHorarioFinal = estarAux.EstarHorarioFinal.AddHours(1);
        //        estarAux.EstarAtivo = estar.EstarAtivo;

        //        if (EstarDAO.AtualizarEstar(estarAux)) {
        //            return RedirectToAction("Index");
        //        }
        //    }
        //    return View(estar);
        //}

        //// GET: Estar/Delete/5
        //public ActionResult Delete(int? id) {
        //    if (id == null) {
        //        return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
        //    }
        //    Estar estar = EstarDAO.BuscarEstarPorId(id);
        //    if (estar == null) {
        //        return HttpNotFound();
        //    }
        //    return View(estar);
        //}

        //// POST: Estar/Delete/5
        //[HttpPost, ActionName("Delete")]
        //[ValidateAntiForgeryToken]
        //public ActionResult DeleteConfirmed(int id) {
        //    Estar estar = EstarDAO.BuscarEstarPorId(id);
        //    EstarDAO.RemoverEstar(estar);
        //    return RedirectToAction("Index");
        //}

    }
}

Harvin/Views/Administrador/Criar.cshtml
@model Harvin.Models.Administrador

@{
    ViewBag.Title = "Criar - Administrador";
    Layout = "~/Views/Shared/TemplateAdmin.cshtml";
}

<h2>Cadastrar</h2>

@using (Html.BeginForm()) {

    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Administrador</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.AdministradorNome, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdministradorNome, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdministradorNome, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradorCpf, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdministradorCpf, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdministradorCpf, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradorTelefone, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdministradorTelefone, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdministradorTelefone, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradorEndereco, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdministradorEndereco, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdministradorEndereco, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradorEmail, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdministradorEmail, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdministradorEmail, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.AdministradorSenha, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.AdministradorSenha, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.AdministradorSenha, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @ViewBag.Mensagem
                <input type="submit" value="Cadastrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Voltar para a Index", "Index")
</div>

Harvin/Views/Administrador/Deletar.cshtml
@model Harvin.Models.Administrador

@{
    ViewBag.Title = "Remover - Administrador";
    Layout = "~/Views/Shared/TemplateAdmin.cshtml";

}

<h2>Remover</h2>

<h3>Você tem certeza disso?</h3>
<div>
    <table class="table">
        <tr>
            <th>@Html.DisplayNameFor(model => model.AdministradorNome)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorCpf)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorTelefone)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorEndereco)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorEmail)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorSenha)</th>
        </tr>

        <tr>
            <td>@Html.DisplayFor(model => model.AdministradorNome)</td>
            <td>@Html.DisplayFor(model => model.AdministradorCpf)</td>
            <td>@Html.DisplayFor(model => model.AdministradorTelefone)</td>
            <td>@Html.DisplayFor(model => model.AdministradorEndereco)</td>
            <td>@Html.DisplayFor(model => model.AdministradorEmail)</td>
            <td>@Html.DisplayFor(model => model.AdministradorSenha)</td>
        </tr>
    </table>
    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Remover" class="btn btn-danger" /> |
            @Html.ActionLink("Voltar para a Index", "Index")
        </div>
    }
</div>

Harvin/Views/Administrador/Detalhes.cshtml
@model Harvin.Models.Administrador

@{
    ViewBag.Title = "Details";
    Layout = "~/Views/Shared/TemplateAdmin.cshtml";
}

<h2>Detalhes</h2>

<div>
    <h4>Administrador</h4>
    <hr />

    <table class="table">
        <tr>

            <th>@Html.DisplayNameFor(model => model.AdministradorNome)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorCpf)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorTelefone)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorEndereco)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorEmail)</th>
            <th>@Html.DisplayNameFor(model => model.AdministradorSenha)</th>
        </tr>
        <tr>
            <td>@Html.DisplayFor(model => model.AdministradorNome)</td>
            <td>@Html.DisplayFor(model => model.AdministradorCpf)</td>
            <td>@Html.DisplayFor(model => model.AdministradorTelefone)</td>
            <td>@Html.DisplayFor(model => model.AdministradorEndereco)</td>
            <td>@Html.DisplayFor(model => model.AdministradorEmail)</td>
            <td>@Html.DisplayFor(model => model.AdministradorSenha)</td>
        </tr>
    </table>
</div>
<p>
    @Html.ActionLink("Editar", "Editar", new { id = Model.AdministradorId }, new { @class = "btn btn-warning btn-sm" })
    @Html.ActionLink("Voltar para Index", "Index", "Administrador", new { @class = "btn btn-default btn-sm" })
</p>

Harvin/Views/Administrador/Index.cshtml
@model IEnumerable<Harvin.Models.Usuario>

@{
    ViewBag.Title = "Administrador - Harvin";

    //LISTA DE ADMINISTRADORES
    List<Harvin.Models.Administrador> ListaAdministradores = new List<Harvin.Models.Administrador>();
    ListaAdministradores = Harvin.DAO.AdministradorDAO.ListarAdministradores();
    List<Harvin.Models.Automovel> ListaAutomoveis = new List<Harvin.Models.Automovel>();
    ListaAutomoveis = Harvin.DAO.AutomovelDAO.ListarAutomoveis();
    List<Harvin.Models.Estar> ListaEstares = new List<Harvin.Models.Estar>();
    ListaEstares = Harvin.DAO.EstarDAO.ListarEstares();

    Layout = "~/Views/Shared/TemplateAdmin.cshtml";

    Harvin.Models.Administrador a = new Harvin.Models.Administrador();
    a = Harvin.DAO.LoginAdminDAO.RetornaAdminLogado();

}

<h2>Bem-Vindo @a.AdministradorNome</h2>

<h3>Usuários</h3>
@Html.ActionLink("Gerencie Usuarios", "IndexConfig", "Usuario", string.Empty, new {@class= "btn btn-primary btn-sm" })
<table class="table">
    <tr>
        <th>
            Nome
        </th>
        <th>
            CPF
        </th>
        <th>
            Telefone
        </th>
        <th>
            Endereço
        </th>
        <th>
            E-mail
        </th>
        <th>
            Saldo
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.UsuarioNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsuarioCpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsuarioTelefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsuarioEndereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsuarioEmail)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UsuarioSaldo)
            </td>
        </tr>
    }

</table>


<h3>Administradores</h3>
<p>
    @Html.ActionLink("Criar Novo", "Criar", "Administrador", string.Empty, new { @class = "btn btn-primary btn-sm" })

</p>
<table class="table">
    <tr>
        <th>
            Nome
        </th>
        <th>
            CPF
        </th>
        <th>
            Telefone
        </th>
        <th>
            Endereço
        </th>
        <th>
            E-mail
        </th>
        <th></th>
    </tr>

    @foreach (var item in ListaAdministradores) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AdministradorNome)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdministradorCpf)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdministradorTelefone)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdministradorEndereco)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AdministradorEmail)
            </td>
            <td>
                @Html.ActionLink("Editar", "Editar", new { id = item.AdministradorId }, new {@class="btn btn-warning btn-sm"})
                @Html.ActionLink("Detalhes", "Detalhes", new { id = item.AdministradorId }, new { @class = "btn btn-success btn-sm" })
                @Html.ActionLink("Deletar", "Deletar", new { id = item.AdministradorId }, new { @class = "btn btn-danger btn-sm" })
            </td>
        </tr>
    }

</table>


<h3>Automoveis</h3>
<table class="table">
    <tr>
        <th>
            Marca
        </th>
        <th>
            Modelo
        </th>
        <th>
            Ano
        </th>
        <th>
            Cor
        </th>
        <th>
            Placa
        </th>
        <th>
            Renavan
        </th>
        <th>
            ID Usuario
        </th>
        <th></th>
    </tr>

    @foreach (var item in ListaAutomoveis) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelMarca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelModelo)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelAno)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelCor)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelPlaca)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelRenavan)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AutomovelUsuarioId)
            </td>
            <td>
                @Html.ActionLink("Detalhes", "Detalhes", "Automovel", new { id = item.AutomovelId }, new { @class = "btn btn-success btn-sm" })
            </td>
        </tr>
    }

</table>


<h3>Estares</h3>
@Html.ActionLink("Veja Estares", "Index", "Estar", string.Empty, new { @class = "btn btn-primary btn-sm" })
<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            ID Usuario
        </th>
        <th>
            ID Automovel
        </th>
        <th>
            Horário Inicial
        </th>
        <th>
            Horário Final
        </th>
    </tr>

    @foreach (var item in ListaEstares) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.EstarId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstarUsuario.UsuarioId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstarAutomovel.AutomovelId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstarDataHorario)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.EstarHorarioFinal)
            </td>
        </tr>
    }

</table>

<h3>Estares Ativos Agora</h3>
<table class="table">
    <tr>
        <th>
            ID
        </th>
        <th>
            ID Usuario
        </th>
        <th>
            ID Automovel
        </th>
        <th>
            Horário Inicial
        </th>
        <th>
            Horário Final
        </th>
    </tr>

    @foreach (var item in ListaEstares) {
        if (DateTime.Now > item.EstarDataHorario && DateTime.Now < item.EstarHorarioFinal) {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.EstarId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstarUsuario.UsuarioId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstarAutomovel.AutomovelId)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstarDataHorario)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EstarHorarioFinal)
                </td>
            </tr>
        }
    }
</table>